import pickle

feature_list=['Spouse,Yes','Spouse,No',
 'Spouse-YN',
 'Adopted Child,Yes',
 'Adopted Child,No',
 'Adopted Child-YN',
 'Stepson or Stepdaughter,Yes',
 'Stepson or Stepdaughter,No',
 'Stepson or Stepdaughter-YN',
 'Self,Yes',
 'Self,No',
 'Self-YN',
 'Child,Yes',
 'Child,No',
 'Child-YN',
 'Life Partner,Yes',
 'Life Partner,No',
 'Life Partner-YN',
 'Grandson or Granddaughter,Yes',
 'Grandson or Granddaughter,No',
 'Grandson or Granddaughter-YN',
 'Ward,Yes',
 'Ward,No',
 'Ward-YN',
 'Dependent on a Minor Dependent,Yes',
 'Dependent on a Minor Dependent,No',
 'Dependent on a Minor Dependent-YN',
 'Guardian,Yes',
 'Guardian,No',
 'Guardian-YN',
 'Court Appointed Guardian,Yes',
 'Court Appointed Guardian,No',
 'Court Appointed Guardian-YN',
 'Sponsored Dependent,Yes',
 'Sponsored Dependent,No',
 'Sponsored Dependent-YN',
 'Foster Child,Yes',
 'Foster Child,No',
 'Foster Child-YN',
 'Son-in-Law or Daughter-in-Law,Yes',
 'Son-in-Law or Daughter-in-Law,No',
 'Son-in-Law or Daughter-in-Law-YN',
 'Ex-Spouse,Yes',
 'Ex-Spouse,No',
 'Ex-Spouse-YN',
 'Brother or Sister,Yes',
 'Brother or Sister,No',
 'Brother or Sister-YN',
 'Nephew or Niece,Yes',
 'Nephew or Niece,No',
 'Nephew or Niece-YN',
 'Collateral Dependent,Yes',
 'Collateral Dependent,No',
 'Collateral Dependent-YN',
 'Annultant,Yes',
 'Annultant,No',
 'Annultant-YN',
 'Other Relationship,Yes',
 'Other Relationship,No',
 'Other Relationship-YN',
 'Father or Mother,Yes',
 'Father or Mother,No',
 'Father or Mother-YN',
 'Other Relative,Yes',
 'Other Relative,No',
 'Other Relative-YN',
 'Stepparent,Yes',
 'Stepparent,No',
 'Stepparent-YN',
 'Grandfather or Grandmother,Yes',
 'Grandfather or Grandmother,No',
 'Grandfather or Grandmother-YN',
 'Uncle or Aunt,Yes',
 'Uncle or Aunt,No',
 'Uncle or Aunt-YN',
 'Cousin,Yes',
 'Cousin,No',
 'Cousin-YN',
 'Brother-in-Law or Sister-in-Law,Yes',
 'Brother-in-Law or Sister-in-Law,No',
 'Brother-in-Law or Sister-in-Law-YN',
 'Father-in-Law or Mother-in-Law,Yes',
 'Father-in-Law or Mother-in-Law,No',
 'Father-in-Law or Mother-in-Law-YN',
 'Trustee,Yes',
 'Trustee,No',
 'Trustee-YN',
 'DomParAsSpouse',
 'SameSexAsSpouse']

def pickle_var(to_be_pickled=feature_list, file_name="pickle"):
    #function was  provided by Nicolas Jacobsohn
    pickle_dir_name = "/data/"
    if to_be_pickled is not None:
        pickle.dump(to_be_pickled, open(pickle_dir_name + file_name + ".p", "wb"))

        pickle_off = open('data/pickle.p',"rb")
        unpickled_list = pickle.load(pickle_off)
        return unpickled_list
    else:
        return "Add file to be pickled"


new_list=pickle_var()
